### ISSUE TITLE
Clicking the extension simply opens my MeTube page (like a bookmark). Nothing starts downloading

### ISSUE THREAD

**Issue by 3shirts** [Rpsl/metube-browser-extension#5]
When I try to use this extension it only opens my MeTube page (like a bookmark) and doesn’t pass the video to download or anything.

**Comment by 3shirts** [comment]
I've tried disabling all other extensions in case it's a conflict and looked in the console, but nothing appears when I click the extension.

**Comment by Rpsl** [comment]
Are you click on extension button near address bar or you click on context menu via right mouse button?

**Comment by Tiritibambix** [comment]
Happens the same to me.
Clicking the extension simply opens my MeTube page.
I have no context menu integration of the addon.

https://i.imgur.com/ps1t0Yh.png

**Comment by Rpsl** [comment]
@tiritibambix yes. at now it's work right that.
1) yes. click on button not send currently open url to metube because some technical reasons. i will fix it in next version
2) context menu integration work on chrome, on youtube links. see [example](https://github.com/Rpsl/metube-browser-extension/blob/master/README.md) and try repeat it
